### PR TITLE
add additional process for computing egfr from creatinine via ckd-epi formula

### PR DESCRIPTION
**Pull request by TaraMirmira**

### CODE REVIEW

**Review by nicholema — COMMENTED** [review]
the formula I used also specify white and black, I do know if it is the best practice to treat the others as white or should we exclude other ethnicity.

**Comment by TaraMirmira** [comment]
> the formula I used also specify white and black, I do know if it is the best practice to treat the others as white or should we exclude other ethnicity.

I can check with Matteo if he knows what the recommended best practice is.

**Comment by TaraMirmira** [comment]
> > the formula I used also specify white and black, I do know if it is the best practice to treat the others as white or should we exclude other ethnicity.
> 
> I can check with Matteo if he knows what the recommended best practice is.

I have confirmed with Matteo that this formula works for all ethnicities. If it looks good to you, I can merge the pull request.

**Comment by nicholema** [comment]
Great it works for all! Sorry I didnt see it before.

**Pull request merged**
